// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yumsy_Backend.Persistence.DbContext;

#nullable disable

namespace Yumsy_Backend.Persistence.Migrations
{
    [DbContext(typeof(SupabaseDbContext))]
    [Migration("20260110143954_AddPostAttributesToTopDailyPostsTable")]
    partial class AddPostAttributesToTopDailyPostsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.AppEventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_app_event_log");

                    b.ToTable("app_event_log", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CommentedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commented_date");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("content");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer")
                        .HasColumnName("likes_count");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comment_parent_comment_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_comment_post_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_user_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.CommentLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comment_like");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_like_comment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_like_user_id");

                    b.ToTable("comment_like", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exception_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_error_log");

                    b.ToTable("error_log", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.HttpLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_http_log");

                    b.ToTable("http_log", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<decimal>("Carbohydrates100g")
                        .HasColumnType("numeric")
                        .HasColumnName("carbohydrates_100g");

                    b.Property<decimal>("EnergyKcal100g")
                        .HasColumnType("numeric")
                        .HasColumnName("energy_kcal_100g");

                    b.Property<decimal>("Fat100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fat_100g");

                    b.Property<decimal?>("Fiber100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fiber_100g");

                    b.Property<string>("MainCategory")
                        .HasColumnType("text")
                        .HasColumnName("main_category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Proteins100g")
                        .HasColumnType("numeric")
                        .HasColumnName("proteins_100g");

                    b.Property<decimal?>("Salt100g")
                        .HasColumnType("numeric")
                        .HasColumnName("salt_100g");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer")
                        .HasColumnName("search_count");

                    b.Property<decimal?>("Sugars100g")
                        .HasColumnType("numeric")
                        .HasColumnName("sugars_100g");

                    b.HasKey("Id")
                        .HasName("pk_ingredient");

                    b.ToTable("ingredient", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.IngredientPost", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("IngredientId", "PostId")
                        .HasName("pk_ingredient_post");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_ingredient_post_post_id");

                    b.ToTable("ingredient_post", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.IngredientShoppingList", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("IngredientId", "ShoppingListId")
                        .HasName("pk_ingredient_shopping_list");

                    b.HasIndex("ShoppingListId")
                        .HasDatabaseName("ix_ingredient_shopping_list_shopping_list_id");

                    b.ToTable("ingredient_shopping_list", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Like", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "PostId")
                        .HasName("pk_like");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_like_post_id");

                    b.ToTable("like", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("comments_count");

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer")
                        .HasColumnName("cooking_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer")
                        .HasColumnName("likes_count");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_date");

                    b.Property<int>("SavedCount")
                        .HasColumnType("integer")
                        .HasColumnName("saved_count");

                    b.Property<int>("SharedCount")
                        .HasColumnType("integer")
                        .HasColumnName("shared_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_post");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_post_user_id");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.PostImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_post_image");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_image_post_id");

                    b.ToTable("post_image", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.PostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("PostId", "TagId")
                        .HasName("pk_post_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_post_tag_tag_id");

                    b.ToTable("post_tag", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.QuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<Guid>("QuizQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_question_id");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("pk_quiz_answer");

                    b.HasIndex("QuizQuestionId")
                        .HasDatabaseName("ix_quiz_answer_quiz_question_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_quiz_answer_tag_id");

                    b.ToTable("quiz_answer", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("mandatory");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<Guid>("TagCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_category_id");

                    b.HasKey("Id")
                        .HasName("pk_quiz_question");

                    b.HasIndex("TagCategoryId")
                        .HasDatabaseName("ix_quiz_question_tag_category_id");

                    b.ToTable("quiz_question", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Recommendation", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("TagId", "UserId")
                        .HasName("pk_recommendation");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recommendation_user_id");

                    b.ToTable("recommendation", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Saved", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.HasKey("UserId", "PostId")
                        .HasName("pk_saved");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_saved_post_id");

                    b.ToTable("saved", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.SeenPost", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("UserId", "PostId")
                        .HasName("pk_seen_post");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_seen_post_post_id");

                    b.ToTable("seen_post", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_from_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_shopping_list");

                    b.HasIndex("CreatedFromId")
                        .HasDatabaseName("ix_shopping_list_created_from_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_shopping_list_user_id");

                    b.ToTable("shopping_list", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.HasKey("Id")
                        .HasName("pk_step");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_step_post_id");

                    b.ToTable("step", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Emote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("emote");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("TagCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_category_id");

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.HasIndex("TagCategoryId")
                        .HasDatabaseName("ix_tag_tag_category_id");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.TagCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tag_category");

                    b.ToTable("tag_category", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.TopDailyPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommentsCount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comments_count");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("LikesCount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("likes_count");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_date");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_top_daily_post");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_top_daily_post_post_id");

                    b.HasIndex("Date", "Rank")
                        .IsUnique()
                        .HasDatabaseName("unique_date_rank");

                    b.ToTable("top_daily_post", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.TopDailyTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("pk_top_daily_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_top_daily_tag_tag_id");

                    b.ToTable("top_daily_tag", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer")
                        .HasColumnName("followers_count");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("integer")
                        .HasColumnName("following_count");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("profile_name");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.Property<int>("RecipesCount")
                        .HasColumnType("integer")
                        .HasColumnName("recipes_count");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.UserFollower", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid")
                        .HasColumnName("following_id");

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("followed_at");

                    b.HasKey("FollowerId", "FollowingId")
                        .HasName("pk_user_follower");

                    b.HasIndex("FollowingId")
                        .HasDatabaseName("ix_user_follower_following_id");

                    b.ToTable("user_follower", (string)null);
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Comment", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Comment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("fk_comment_comment_parent_comment_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_post_post_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_user_user_id");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.CommentLike", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_like_comment_comment_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "User")
                        .WithMany("CommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_like_user_user_id");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.IngredientPost", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientPosts")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_post_ingredient_ingredient_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany("IngredientPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_post_post_post_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.IngredientShoppingList", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientShoppingLists")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_shopping_list_ingredient_ingredient_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.ShoppingList", "ShoppingList")
                        .WithMany("IngredientShoppingLists")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_shopping_list_shopping_list_shopping_list_id");

                    b.Navigation("Ingredient");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Like", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_like_post_post_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_like_user_user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Post", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "CreatedBy")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_user_user_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.PostImage", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_image_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.PostTag", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_tag_post_post_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_tag_tag_tag_id");

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.QuizAnswer", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.QuizQuestion", "QuizQuestion")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_answer_quiz_question_quiz_question_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.Tag", "Tag")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("TagId")
                        .HasConstraintName("fk_quiz_answer_tag_tag_id");

                    b.Navigation("QuizQuestion");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.QuizQuestion", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.TagCategory", "TagCategory")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("TagCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_question_tag_category_tag_category_id");

                    b.Navigation("TagCategory");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Recommendation", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Tag", "Tag")
                        .WithMany("Recommendations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_tag_tag_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_user_user_id");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Saved", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany("Saved")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_post_post_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "User")
                        .WithMany("Saved")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_user_user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.SeenPost", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seen_post_post_post_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seen_post_user_user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.ShoppingList", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "CreatedFrom")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("CreatedFromId")
                        .HasConstraintName("fk_shopping_list_post_created_from_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "User")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_user_user_id");

                    b.Navigation("CreatedFrom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Step", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany("Steps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_step_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Tag", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.TagCategory", "TagCategory")
                        .WithMany("Tags")
                        .HasForeignKey("TagCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_tag_category_tag_category_id");

                    b.Navigation("TagCategory");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.TopDailyPost", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_top_daily_post_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.TopDailyTag", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_top_daily_tag_tag_tag_id");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.UserFollower", b =>
                {
                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "Follower")
                        .WithMany("Followings")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_follower_user_follower_id");

                    b.HasOne("Yumsy_Backend.Persistence.Models.User", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_follower_user_following_id");

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Comment", b =>
                {
                    b.Navigation("ChildComments");

                    b.Navigation("CommentLikes");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Ingredient", b =>
                {
                    b.Navigation("IngredientPosts");

                    b.Navigation("IngredientShoppingLists");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("IngredientPosts");

                    b.Navigation("Likes");

                    b.Navigation("PostImages");

                    b.Navigation("PostTags");

                    b.Navigation("Saved");

                    b.Navigation("ShoppingLists");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.QuizQuestion", b =>
                {
                    b.Navigation("QuizAnswers");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.ShoppingList", b =>
                {
                    b.Navigation("IngredientShoppingLists");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.Tag", b =>
                {
                    b.Navigation("PostTags");

                    b.Navigation("QuizAnswers");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.TagCategory", b =>
                {
                    b.Navigation("QuizQuestions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Yumsy_Backend.Persistence.Models.User", b =>
                {
                    b.Navigation("CommentLikes");

                    b.Navigation("Comments");

                    b.Navigation("Followers");

                    b.Navigation("Followings");

                    b.Navigation("Likes");

                    b.Navigation("Posts");

                    b.Navigation("Recommendations");

                    b.Navigation("Saved");

                    b.Navigation("ShoppingLists");
                });
#pragma warning restore 612, 618
        }
    }
}
